// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/blablatov/bidistream-mtls-grpc/bs-mtls-proto (interfaces: OrderManagementClient)

// Package mock_bs_mtls_proto is a generated GoMock package.
package mock_bs_mtls_proto

import (
	context "context"
	reflect "reflect"

	__ "github.com/blablatov/bidistream-mtls-grpc/bs-mtls-proto"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOrderManagementClient is a mock of OrderManagementClient interface.
type MockOrderManagementClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderManagementClientMockRecorder
}

// MockOrderManagementClientMockRecorder is the mock recorder for MockOrderManagementClient.
type MockOrderManagementClientMockRecorder struct {
	mock *MockOrderManagementClient
}

// NewMockOrderManagementClient creates a new mock instance.
func NewMockOrderManagementClient(ctrl *gomock.Controller) *MockOrderManagementClient {
	mock := &MockOrderManagementClient{ctrl: ctrl}
	mock.recorder = &MockOrderManagementClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderManagementClient) EXPECT() *MockOrderManagementClientMockRecorder {
	return m.recorder
}

// ProcessOrders mocks base method.
func (m *MockOrderManagementClient) ProcessOrders(arg0 context.Context, arg1 ...grpc.CallOption) (__.OrderManagement_ProcessOrdersClient, error) {
	//m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessOrders", varargs...)
	ret0, _ := ret[0].(__.OrderManagement_ProcessOrdersClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessOrders indicates an expected call of ProcessOrders.
func (mr *MockOrderManagementClientMockRecorder) ProcessOrders(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	//mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOrders", reflect.TypeOf((*MockOrderManagementClient)(nil).ProcessOrders), varargs...)
}
